vblogger/config/routes.rb
Vblogger::Application.routes.draw do
  

  get "blogs/myblogs"
  get "login/index"
  get "login/signup"
  post "login/signupprocess"
  post "login/validate"
  post "application/clearsession"
  get "application/getsessionforjs"

  resources :blogs do
    resources :posts do
      resources :comments
    end
  end

  root 'login#index'

end

vblogger/app/models/blog.rb
class Blog < ActiveRecord::Base
	has_many :posts
end

vblogger/app/models/blogger.rb
class Blogger < ActiveRecord::Base
end

vblogger/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

vblogger/app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :blog

  has_many :comments
end

vblogger/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
  
  before_filter :set_gon
  

  def clearsession
  	reset_session
  	set_gon
  	redirect_to login_index_path, :notice=>"Logout successful"
  end

  def getsessionforjs
	  	
  end

  def set_gon
   		@loggedblogger = session[:loggedblogger]
   		gon.watch.sessionuser = @loggedblogger
   		#gon.watch.test = 0
  end

  private

  	


end

vblogger/app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @blogs = Blog.all
  end

  def myblogs
    @loggedblogger = session[:loggedblogger]
    @blogs = Blog.where(["bloggerid = ?", @loggedblogger[:bloggerid]])
  end

  def new
    @blog = Blog.new
  end

  def create
    @loggedblogger = session[:loggedblogger]
    @latestblog = Blog.order("blogid DESC").first
    @latestblogid = getLatestBlogID(@latestblog ? @latestblog[:blogid] : "empty")
    @parameters = {:blogid => @latestblogid, :bloggerid => @loggedblogger[:bloggerid]}
    @parameters.merge!(post_params)
    @parameters[:numberofposts] = 0

    @blog = Blog.new(@parameters)

    if @blog.save
      redirect_to blog_path(@blog), :notice => "Blog created successfully"
    else
      render "new"
    end


  end

  def show
    @blog = Blog.find(params[:id]) 
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private
    def post_params
        params.require(:blog).permit(:blogtitle, :blogdescription)
      end

    def getLatestBlogID(id)
      if id == "empty"
        newid = "BLOG" + Time.now.strftime("%Y%m%d") + "0001"
      else
        latestiddate = id[4,8]
        today = Time.now.strftime("%Y%m%d")

        #if latestiddate = today then increment id by 1
        if latestiddate == today
          newid = "BLOG" + (id[4,12].to_i + 1).to_s
        #else create new id with today's date
        else
           newid = "BLOG" + Time.now.strftime("%Y%m%d") + "0001"
        end  
      end
    end

end

vblogger/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@blog = Blog.find(params[:blog_id])
	    @post = Post.find(params[:post_id])
		@loggedblogger = session[:loggedblogger]

		@latestcomment = @post.comments.order("commentid DESC").first
    	@latestcommentid = getLatestCommentID(@latestcomment ? @latestcomment[:commentid] : "empty")
	    
	    @parameters = {:commentid=>@latestcommentid,:postid=>@post[:postid],:bloggerid=>@loggedblogger[:bloggerid]}
	    @parameters.merge!(post_params)

	    @comment = @post.comments.create(@parameters)
		redirect_to "/blogs/#{@blog.id}/posts/#{@post.id}"
	end


	private
		def post_params
    		params.require(:comment).permit(:commenttext)
  		end
  		def getLatestCommentID(id)
		  if id == "empty"
		    newid = "CMNT" + Time.now.strftime("%Y%m%d") + "0001"
	      else
			latestiddate = id[4,8]
	      	today = Time.now.strftime("%Y%m%d")

		    #if latestiddate = today then increment id by 1
		    if latestiddate == today
		      newid = "CMNT" + (id[4,12].to_i + 1).to_s
		    #else create new id with today's date
		    else
		       newid = "CMNT" + Time.now.strftime("%Y%m%d") + "0001"
		    end
	      end		
	    end
end

vblogger/app/controllers/login_controller.rb
class LoginController < ApplicationController
	def index
		@blogger = Blogger.new
	end

	def validate
		@data = params[:blogger]
		@blogger = Blogger.find_by username: @data[:username]

		#@flag = "empty"	if  @loggedblogger == nil
		#@flag = @loggedblogger[:name] if @loggedblogger != nil
		if !@blogger
			redirect_to login_index_path, :notice => "User not found."
		else
			if @blogger[:username] == @data[:username] && @blogger[:password] == @data[:password]
				session[:loggedblogger] = @blogger
				redirect_to blogs_path, :notice => "Login successful"
			else
				redirect_to login_index_path, :notice => "Login unsuccessful"
			end
		end

	end
	


	def signup
		@blogger = Blogger.new
	end
	def signupprocess
		@latestblogger = Blogger.order("bloggerid DESC").first
		@latestbloggerid = getLatestBloggerID(@latestblogger ? @latestblogger[:bloggerid] : "empty")
		@parameters = {:bloggerid => @latestbloggerid}
		@parameters.merge!(post_params)

		@blogger = Blogger.new(@parameters)

		if @blogger.save
			redirect_to login_index_path, :notice => "Registration complete. Login to continue"
		else
			render "signup"
		end
	end

	private
		def post_params
    		params.require(:blogger).permit(:name, :username, :email, :password)
  		end

		def getLatestBloggerID(id)
			if id == "empty"
			   	newid = "BLGR" + Time.now.strftime("%Y%m%d") + "0001"
			else
				latestiddate = id[4,8]
				today = Time.now.strftime("%Y%m%d")

				#if latestiddate = today then increment id by 1
				if latestiddate == today
					newid = "BLGR" + (id[4,12].to_i + 1).to_s
				#else create new id with today's date
				else
				   newid = "BLGR" + Time.now.strftime("%Y%m%d") + "0001"
				end
			end
		end
end

#s="BLGR201404050005"
#latestiddate = s[4,8]
#today = Time.now.strftime("%Y%m%d")
#if latestiddate == today
#   newid = "BLGR" + (s[4,12].to_i + 1).to_s
#else
#   newid = "BLGR" + Time.now.strftime("%Y%m%d") + "0001"
#end

vblogger/app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@blog = Blog.find(params[:blog_id])
		@posts = Post.where(["blogid = ?", @blog[:blogid]])
	end
	def new
		@blog = Blog.find(params[:blog_id])
		@post = Post.new
	end
	def create
		@loggedblogger = session[:loggedblogger]
		@blog = Blog.find(params[:blog_id])
		
		@latestpost = Post.order("postid DESC").first
    	@latestpostid = getLatestPostID(@latestpost ? @latestpost[:postid] : "empty")
    
		@parameters = {:postid => @latestpostid, :blogid => @blog[:blogid] , :bloggerid => @loggedblogger[:bloggerid]}
		@parameters.merge!(post_params)
		@post = Post.new(@parameters)
		
		if @post.save
			redirect_to blog_posts_path(@blog), :notice => "Post saved successfully !"
		else
			render "new"
		end
	end
	def show
		@blog = Blog.find(params[:blog_id])
		@post = Post.find(params[:id])
		@comment = Comment.new
	end
	def edit
		@blog = Blog.find(params[:blog_id])
		@post = Post.find(params[:id])
	end
	def update
		@post = Post.find(params[:id])
		@blog = Blog.find(params[:blog_id])

		if @post.update_attributes(post_params)
			redirect_to blog_posts_path(@blog), :notice => "Post edited successfully !"
		else
			render "edit"
		end
	end
	def destroy
		@post = Post.find(params[:id])
		@blog = Blog.find(params[:blog_id])

		@post.destroy
		redirect_to blog_posts_path(@blog), :notice => "Post deleted successfully !"
	end
  
	private
		def post_params
    		params.require(:post).permit(:title, :content)
  		end
	
		def getLatestPostID(id)
		  if id == "empty"
		    newid = "POST" + Time.now.strftime("%Y%m%d") + "0001"
	      else
			latestiddate = id[4,8]
	      	today = Time.now.strftime("%Y%m%d")

		    #if latestiddate = today then increment id by 1
		    if latestiddate == today
		      newid = "POST" + (id[4,12].to_i + 1).to_s
		    #else create new id with today's date
		    else
		       newid = "POST" + Time.now.strftime("%Y%m%d") + "0001"
		    end
	      end		
	    end

end

vblogger/app/helpers/blogs_helper.rb
module BlogsHelper
end

vblogger/app/helpers/comments_helper.rb
module CommentsHelper
end

vblogger/app/helpers/login_helper.rb
module LoginHelper
end

vblogger/app/helpers/posts_helper.rb
module PostsHelper
end

vblogger/app/views/blogs/create.html.erb
<h1>Blogs#create</h1>
<p>Find me in app/views/blogs/create.html.erb</p>

vblogger/app/views/blogs/destroy.html.erb
<h1>Blogs#destroy</h1>
<p>Find me in app/views/blogs/destroy.html.erb</p>

vblogger/app/views/blogs/edit.html.erb
<h1>Blogs#edit</h1>
<p>Find me in app/views/blogs/edit.html.erb</p>

vblogger/app/views/blogs/index.html.erb
<h1>All Blogs</h1>

<% @blogs.each do |blog| %>
	<p>
		<h2>
			<%= link_to blog.blogtitle, blog_path(blog) %>
		</h2>
	</p>
	<p>
		Description: <%= blog.blogdescription %>
	</p>
	<% @blogger = Blogger.find_by bloggerid: blog.bloggerid %>
	<p>
		Author: <%= @blogger.name %>
	</p>
	
<% end %>

vblogger/app/views/blogs/myblogs.html.erb
<h1>My Blogs</h1>

<%= form_for Blogger.new, url: new_blog_path, method: :get do |newblogform| %>
	<%= newblogform.submit "Create a new blog" %>
<% end %>

<% @blogs.each do |blog| %>
	<p>
		<h2>
			<%= link_to blog.blogtitle, blog_path(blog) %>
		</h2>
	</p>
	<p>
		Description: <%= blog.blogdescription %>
	</p>
	<% @blogger = Blogger.find_by bloggerid: blog.bloggerid %>
	<p>
		Author: <%= @blogger.name %>
	</p>
	
<% end %>

vblogger/app/views/blogs/new.html.erb
<h1>Create a new blog</h1>

<%= form_for @blog do |newblogform| %>
	<p>
		<%= newblogform.label :blogtitle, "Blog Title" %>
	</p>
	<p>
		<%= newblogform.text_field :blogtitle %>
	</p>
	<p>
		<%= newblogform.label :blogdescription, "Description" %>
	</p>
	<p>
		<%= newblogform.text_area :blogdescription %>
	</p>
	<p>
		<%= newblogform.submit "Create" %>
	</p>

<% end  %>

vblogger/app/views/blogs/show.html.erb
<h1><%= @blog.blogtitle %></h1>
<p>
	<%= @blog.blogdescription %>
</p>
<% @blogger = Blogger.find_by bloggerid: @blog.bloggerid %>
<p>
	Author: <%= @blogger.name %>
</p>
<p>
	<%= link_to "View all posts", blog_posts_path(@blog) %>
</p>
<% @loggedblogger = session["loggedblogger"] %>
<% if @blogger.bloggerid == @loggedblogger.bloggerid %>
<p>
	<%= link_to "Add new post", new_blog_post_path(@blog) %>
</p>
<% end %>

vblogger/app/views/blogs/update.html.erb
<h1>Blogs#update</h1>
<p>Find me in app/views/blogs/update.html.erb</p>

vblogger/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Vblogger</title>
	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= csrf_meta_tags %>
	<%= favicon_link_tag 'favicon.ico' %>
	<%= include_gon(watch: true) %>
	<script type="text/javascript">
		var t=0;
		$(document).ready(function(){
			$('.username').mouseenter(function(){
				$('.logout').show();
				$('.username').addClass('loggingout');
			}).mouseleave(function(){
				$('.logout').mouseenter(function(){
					$('.logout').show();
					$('.username').addClass('loggingout');
				}).mouseleave(function(){
					$('.logout').hide();
					$('.username').removeClass('loggingout');
				});
				$('.username').mouseover(function(){
					$('.logout').show();
					$('.username').addClass('loggingout');
				});
				$('.logout').hide();
				$('.username').removeClass('loggingout');
			});
			
		});
		$(window).focus(function(){
				var form = $('#form_getsessionforjs');
				var getsessionforjsURL = form.attr('action');
				//alert(getsessionforjsURL);
				//$.ajax({
				//	type: "GET",
				//	url: getsessionforjsURL,
				//	success: function(data){
				//		alert(1);
				//	}
				//});
				t = gon.watch('sessionuser');
				if(typeof t == 'object')
					console.log('its an obj');
				jQuery.globalEval(t);
				console.log(t.readyState);
		});
	</script>
	<style type="text/css">


	</style>
</head>
<body>

<header id = "navbar">
	<%= form_for Blogger.new, url: application_getsessionforjs_path, method: :post, :html => { :id => "form_getsessionforjs" } do |f| %>
	<% end %>

	<div id="logo-wrapper">
		<div id="site-logo" class="logo-wrapper-item"></div>
		<div id="site-title" class="logo-wrapper-item">V-Blogger</div>
	</div>

	<% if request.fullpath.to_s.include? "login/" or request.fullpath.to_s.end_with? "/" %>
		<% if session[:loggedblogger] %>	
			<script type="text/javascript">
	    		window.location.href="/blogs"
	  		</script>
	  	<% end %>
	<% end %>
	<% if !request.fullpath.to_s.include? "login/" %>
		<% if !session[:loggedblogger] %>
			<script type="text/javascript">
	    		window.location.href="/login/index"
	  		</script>			
		<% elsif session[:loggedblogger] %>
			<div id = "navmenu">
				<div class="navitem">
					<%= link_to "Home", blogs_path %>
				</div>
				<div class="navitem">
					<%= link_to "My Blogs", blogs_myblogs_path %>
				</div>
				<div class="navitem username">
					<% loggedblogger = session[:loggedblogger] %>
					<%= loggedblogger[:name] %>
					<div class="logout" style="display: none">
						<%= form_for Blogger.new, url: application_clearsession_path do |logoutform| %>
							<%= logoutform.submit "Logout", :class => "btn-logout" %>
						<% end %>
					</div>
				</div>	
				
			</div>
			
			
			
				
			
	  	<% end %>
	<% end %>
</header>


<div class="main-container">
	<% flash.each do |key,value| %>
		<p><%= value %></p>
	<% end %>

	<%= yield %>	
</div>


</body>
</html>

vblogger/app/views/login/index.html.erb
<h1>Login</h1>

<%= form_for @blogger, url: login_validate_path , method: :post do |f| %>
	<p>
		<%= f.label :username, "Username" %>
	</p>
	<p>
		<%= f.text_field :username %>
	</p>
	<p>
		<%= f.label :password, "Password" %>
	</p>
	<p>
		<%= f.password_field :password %>
	</p>
	<p>
		<%= f.submit "Login" %>
	</p>
	
<% end %>
<%= link_to "Sign Up", login_signup_path %>

vblogger/app/views/login/signup.html.erb
<h1>Signup</h1>

<%= form_for @blogger, url: login_signupprocess_path , method: :post do |signupform| %>
	<p>
		<%= signupform.label :name, "Name" %>
	</p>
	<p>
		<%= signupform.text_field :name %>
	</p>
	<p>
		<%= signupform.label :email, "Email" %>
	</p>
	<p>
		<%= signupform.text_field :email %>
	</p><p>
		<%= signupform.label :username, "Username" %>
	</p>
	<p>
		<%= signupform.text_field :username %>
	</p>
	<p>
		<%= signupform.label :password, "Password" %>
	</p>
	<p>
		<%= signupform.password_field :password %>
	</p>
	<p>
		<%= signupform.label :repassword, "Re-enter password" %>
	</p>
	<p>
		<%= signupform.password_field :repassword %>
	</p>
	<p>
		<%= signupform.submit "Signup" %>
	</p>

<% end %>

vblogger/app/views/posts/create.html.erb
<%= @parameters %>

vblogger/app/views/posts/edit.html.erb
<h1>
	<%= link_to @blog.blogtitle, blog_path(@blog) %>
</h1>

<h1>Edit Post</h1>

<%= form_for @post, url: "/blogs/#{@blog.id}/posts/#{@post[:id]}", method: :patch do |f| %>
	<p>
		<%= f.label :title %>
	</p>
	<p>
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :content %>
	</p>
	<p>
		<%= f.text_area :content %>
	</p>
	
	<%= f.submit "Edit post" %>
<% end %>

vblogger/app/views/posts/index.html.erb
<% @blogger = Blogger.find_by bloggerid: @blog.bloggerid %>
<% @loggedblogger = session["loggedblogger"] %>

<h1>
	<%= link_to @blog.blogtitle, blog_path(@blog) %>
</h1>

<h2>All Posts</h2>

<% @posts.each do |post| %>
	<p>
		<h2>
			<%= link_to post.title, "/blogs/#{@blog.id}/posts/#{post.id}" %>
		</h2>
		<%= post.created_at %>
	</p>
	<p>
		<%= post.content %>
	</p>
	<% @blogger = Blogger.find_by bloggerid: post.bloggerid %>
	<p>
		Author: <%= @blogger.name %>
	</p>
	<% if @blogger.bloggerid == @loggedblogger.bloggerid %>
		<p>
			<%= link_to "Edit", "/blogs/#{@blog.id}/posts/#{post.id}/edit" %> |
			<%= link_to "Delete", "/blogs/#{@blog.id}/posts/#{post.id}", :confirm => "Are you sure you want to delete this post ?", :method => :delete %>
		</p>
	<% end %>
	<hr/>	
<% end %>

<% if @blogger.bloggerid == @loggedblogger.bloggerid %>
<p>
	<%= link_to "Add new post", new_blog_post_path(@blog) %>
</p>
<% end %>

vblogger/app/views/posts/new.html.erb
<h1>
	<%= link_to @blog.blogtitle, blog_path(@blog) %>
</h1>

<h2>New Post</h2>


<%= form_for @post, url: "/blogs/#{@blog.id}/posts", method: :post do |f| %>
	<p>
		<%= f.label :title, "Title of the post" %>
	</p>
	<p>
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :content, "Body of the post"%>
	</p>
	<p>
		<%= f.text_area :content %>
	</p>
	
	<%= f.submit "Add new post" %>
<% end %>

vblogger/app/views/posts/show.html.erb
<h1>
	<%= @post.title %>
</h1>
<p>
	<%= @post.content %>
</p>
<p>
	<%= @post.created_at %>
</p>

<h2>Comments</h2>
<% @post.comments.each do |comment| %>

  <% @commenter = Blogger.find_by bloggerid: comment.bloggerid%>
  <p>
  	<strong><%= @commenter.name %>:</strong>
    <%= comment.commenttext %>
  </p>
<% end %>
<% @loggedblogger = session[:loggedblogger] %>
<strong><%= @loggedblogger.name %> -</strong>
<%= form_for @comment, url: "/blogs/#{@blog.id}/posts/#{@post[:id]}/comments", method: :post do |f| %>
  <p>
    <%= f.text_area :commenttext %>
  </p>
  <p>
    <%= f.submit "Add a comment" %>
  </p>
<% end %>